export const navbarLinks: { href: string; type: 'navbar'; text: string }[] = [
  { href: '', type: 'navbar', text: 'Todo' },
  { href: '', type: 'navbar', text: 'En directo' },
  { href: '', type: 'navbar', text: 'Videojuegos' },
  { href: '', type: 'navbar', text: 'Música' },
  { href: '', type: 'navbar', text: 'Deep House' },
  { href: '', type: 'navbar', text: 'Listas de reproducción' },
  { href: '', type: 'navbar', text: 'Disco' },
  { href: '', type: 'navbar', text: 'Álbumes' },
  { href: '', type: 'navbar', text: 'Jazz' },
  { href: '', type: 'navbar', text: 'Reggaeton' },
  { href: '', type: 'navbar', text: 'Risas' },
  { href: '', type: 'navbar', text: 'Pop latino' },
  { href: '', type: 'navbar', text: 'Historia' },
  { href: '', type: 'navbar', text: 'Comedia' },
  { href: '', type: 'navbar', text: 'Rock alternativo' },
  { href: '', type: 'navbar', text: 'Música new age' },
  { href: '', type: 'navbar', text: 'Música independiente' },
  { href: '', type: 'navbar', text: 'Música clássica' },
  { href: '', type: 'navbar', text: 'Minecraft' },
  { href: '', type: 'navbar', text: 'Subidas recientes' },
];
